--js-runtimes
deno
--extractor-args
youtube:player_client=web_safari,web,mweb,android
--format
bestaudio[protocol=https]/bestaudio[protocol^=http]/bestaudio/best
--downloader
ffmpeg
--retries
10
--fragment-retries
10
